/**
 * dev/genFixtures.js - NODE-ONLY. Generates Fixtures.js by extracting the body
 * of representative .eml files and embedding them as escaped JS string literals
 * (GAS has no filesystem access at runtime, so tests need embedded bodies).
 *
 * We embed three fixtures spanning the section combinations:
 *   eraA_2018 - legacy: Summary + Zones only            (quoted-printable)
 *   eraB_2019 - modern: + Header + Treadmill (no rower)  (quoted-printable)
 *   eraC_2025 - modern: + Rower + Steps + Peak HR        (7bit)
 */
const fs = require('fs');
const path = require('path');
const { readEmlBody, ROOT } = require('./harness');

const PICK = {
  eraA_2018: 'fixtures/eraA_2018-03-19.eml',
  eraB_2019: 'fixtures/eraB_2019-07-16.eml',
  eraC_2025: 'fixtures/eraC_2025-11-current.eml',
};

let out = `/**
 * Fixtures.js - GENERATED by dev/genFixtures.js. Do not edit by hand.
 *
 * Embedded raw email bodies (still transfer-encoded for the QP fixtures) used by
 * Tests.js, since Apps Script cannot read the local .eml files at runtime.
 */

var FIXTURES_RAW = {
`;

for (const [id, rel] of Object.entries(PICK)) {
  const body = readEmlBody(path.join(ROOT, rel));
  out += `  ${id}: ${JSON.stringify(body)},\n`;
}

out += `};

/** Return the embedded raw body for a fixture id. */
function getFixture(id) {
  return FIXTURES_RAW[id];
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { FIXTURES_RAW: FIXTURES_RAW, getFixture: getFixture };
}
`;

fs.writeFileSync(path.join(ROOT, 'Fixtures.js'), out);
console.log('Wrote Fixtures.js (' + out.length + ' bytes)');
